/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.app1;

import java.util.Scanner;

public class App2 {

  static Scanner keyScan = new Scanner(System.in);

  public static void main(String[] args) {
    Console2 console2 = new Console2();
    CommandHandler2 commandHandler2 = new CommandHandler2();

    while(true) {
      Command2 command2 = console2.prompt();

      if (command2.getName().equals("quit") || command2.getName().equals("exit")) {
        break;

      } else if (command2.getName().equals("")) {
        continue;

      } else if (command2.getName().equals("help")) {
        commandHandler2.doHelp();

      } else if (command2.getName().equals("add")){
        commandHandler2.doAdd(command2);

      } else if (command2.getName().equals("minus")){
        commandHandler2.doMinus(command2);

      } else {
        System.out.println("지원하지 않는 연산자입니다.");
      }
    }

    console2.close();
  }


}



